-- ============================================================
-- Seed the projects table with the 9 current missions.
-- Run AFTER schema.sql. Idempotent: re-running updates existing rows by code.
-- ============================================================

insert into public.projects
  (code, title, tech, summary, stack, hook, brief, role, method, outcome, chips, status, sort_order, published)
values
  ('MSN-02', 'Fraud Triage', 'XGBoost / Gemini',
   '0.978 AUC; caught fraud the base model missed.',
   'XGBoost / Google Gemini / Python',
   'A two-stage pipeline that catches what the model misses.',
   'Built on 284,807 real card transactions. XGBoost scores every transaction at scale; a reasoning layer reviews only the high-risk flags and writes a structured, analyst-ready verdict. Weighted loss took AUC from 0.60 to 0.978, and in testing the second layer caught a fraud the model had scored a perfect 0.000000.',
   'Solo build, end to end',
   'Weighted-loss XGBoost plus a triage layer with strict JSON output',
   'Industry-grade AUC with a reasoning trail analysts can audit',
   array['0.978 AUC','84% Recall','84% Precision','284K Records','~2s Latency'],
   'deployed', 10, true),

  ('MSN-03', 'Corporate Analytics', 'Power BI / SQL',
   '30% faster executive reviews via custom dashboards.',
   'Power BI / DAX / SQL',
   '30% faster executive reviews via custom dashboards.',
   'Executive Power BI dashboards built on live B2B data streams for TapInnovations, replacing a legacy spreadsheet workflow. Custom DAX measures gave leadership direct visibility into cross-functional throughput, and weekly performance reviews accelerated by 30%.',
   'Analyst + stakeholder liaison',
   'Custom DAX measures on live B2B data streams',
   'Weekly executive reviews 30% faster, spreadsheets retired',
   array['30% Faster Reviews','Live B2B Streams','Custom DAX','Exec-Ready'],
   'deployed', 20, true),

  ('MSN-10', 'Heart Disease Prediction', 'Python / Scikit-learn',
   '~82% accuracy; best of 5 models; live Flask app.',
   'Python / Scikit-learn / Flask',
   '~82% accuracy, deployed as a Flask app.',
   'End-to-end capstone comparing five classifiers on the 13-feature clinical heart dataset. Random Forest was the strongest at ~82% accuracy; a top-3 majority-vote ensemble landed just behind, served through a Flask web app that scores risk from a 13-field form.',
   'Capstone lead',
   'Five-model comparison on a 13-feature clinical set, served via Flask',
   '~82% Random Forest accuracy, best of five models, in a live app',
   array['~82% Accuracy','5 Models Compared','13 Features','Flask App'],
   'archived', 90, true),

  ('MSN-04', 'Hospital Readmission', 'Python / Gradient Boosting',
   '90% recall on readmissions via threshold tuning.',
   'Python / Scikit-learn / Gradient Boosting',
   '90% recall on readmissions through threshold tuning.',
   'Readmission risk on 25,000 anonymized encounters, a Python rebuild of a tool-based analysis. Logistic Regression, Random Forest, and Gradient Boosting were compared; the champion (Gradient Boosting, ROC-AUC 0.66) was threshold-tuned to catch 90% of readmissions, the costly case to miss. Prior inpatient visits, medication count, and lab procedures were the dominant drivers.',
   'Solo analysis',
   'Three-model comparison with a recall-tuned decision threshold',
   '90% of readmissions caught (ROC-AUC 0.66) before discharge',
   array['25K Records','90% Recall','ROC-AUC 0.66','Threshold Tuned'],
   'deployed', 30, true),

  ('MSN-05', 'Auto Insurance Churn', 'Gradient Boosting / SMOTE',
   'ROC-AUC 0.70 on 92,849 policyholders.',
   'Scikit-learn / Gradient Boosting / SMOTE',
   'Churn modeling on 92,849 policyholders.',
   'Five classifiers on 92,849 policyholder records with severe class imbalance (11.5% churn). A SMOTE pipeline plus a data-leakage fix (dropping a column only set after churn) put Gradient Boosting on top at ROC-AUC 0.70, threshold-tuned for recall, replacing an earlier run that had crowned a near-random model.',
   'Solo build',
   'Five-model comparison on a SMOTE pipeline, champion chosen by ROC-AUC',
   'Gradient Boosting champion at ROC-AUC 0.70, tuned for recall',
   array['92.8K Records','ROC-AUC 0.70','SMOTE Pipeline','GB Champion'],
   'deployed', 40, true),

  ('MSN-06', 'Supply Chain Opt.', 'HBP Simulation / Python',
   '34% cumulative margin across 4-year horizon.',
   'HBP Simulation / Inventory Strategy',
   '34% cumulative margin across a 4-year horizon.',
   'Managed a simulated global supply chain through four years of high demand volatility. A hybrid sourcing strategy with statistical inventory buffering held a 98% service level with zero stockouts while maximizing gross margin.',
   'Strategy lead',
   'Hybrid sourcing with statistical inventory buffering',
   '34% margin at a 98% service level, zero stockouts',
   array['34% Margin','98% Service Level','Zero Stockouts','Hybrid Sourcing'],
   'archived', 60, true),

  ('MSN-07', 'Bullwhip Mitigation', 'HBP Simulation / Sourcing',
   '54% gross margin under demand volatility.',
   'HBP Simulation / Sourcing Strategy',
   '54% gross margin under demand volatility.',
   'A four-year product lifecycle and supplier risk simulation. Engineered a hybrid sourcing strategy balancing low-cost overseas suppliers against high-flexibility nearshore ones, managing product design upgrades and volatile demand to close at a 54% cumulative gross margin.',
   'Strategy lead',
   'Hybrid sourcing balanced across offshore and nearshore suppliers',
   '54% cumulative gross margin under the bullwhip effect',
   array['54% Gross Margin','Hybrid Sourcing','4-Year Horizon','Supplier Risk'],
   'archived', 70, true),

  ('MSN-08', 'Prime Air Drone Logistics', 'Geospatial / Network Design',
   'Hub-and-spoke last-mile delivery model.',
   'Geospatial Analysis / Network Design',
   'A hub-and-spoke last-mile delivery model.',
   'Last-mile feasibility study for suburban drone delivery in Massachusetts. Demographic and geospatial analysis identified optimal hub placement under payload, flight-range, and urban-restriction constraints, packaged as a 12-month phased rollout designed to cut last-mile lead times.',
   'Network designer',
   'Geospatial and demographic constraint analysis',
   'Suburban hub-and-spoke model with a 12-month rollout plan',
   array['Hub-and-Spoke','Geospatial','12-Month Roadmap','Constraint Model'],
   'in_progress', 80, true),

  ('MSN-09', 'Strategy Summit', 'CAPSIM Simulation / Strategy',
   '483% stock recovery; top-3 of 8 teams.',
   'CAPSIM Simulation / Pricing / Capacity',
   '483% stock recovery, top-3 of 8 teams.',
   'Ran a simulated sensor manufacturer across R&D, marketing, production, and finance for five simulated years. Calibrated pricing tiers and capacity against rate-sensitive demand, recovering the share price from $1.40 to $8.17 and finishing top-3 in cumulative profit. Recognized for an alternating high-tech product strategy.',
   'Team decision lead',
   'Pricing and capacity calibration across 5 simulated years',
   'Share price from $1.40 to $8.17, top-3 cumulative profit',
   array['483% Recovery','$1.40 to $8.17','Top-3 of 8','5 Sim Years'],
   'archived', 90, true)

on conflict (code) do update set
  title = excluded.title, tech = excluded.tech, summary = excluded.summary,
  stack = excluded.stack, hook = excluded.hook, brief = excluded.brief,
  role = excluded.role, method = excluded.method, outcome = excluded.outcome,
  chips = excluded.chips, status = excluded.status,
  sort_order = excluded.sort_order, published = excluded.published;
