-- ============================================================
-- Seed the projects table with the 12 current missions.
-- Run AFTER schema.sql. Idempotent: re-running updates existing rows by code.
-- Generated from the live table; regenerate rather than hand-editing.
-- ============================================================

insert into public.projects
  (code, title, tech, summary, stack, hook, brief, role, method, outcome, chips, skills, status, status_label, sort_order, published, github_url, show_status, show_github, link_type)
values
  ('MSN-01',
   'Invitovate',
   'Postgres + RLS / Vanilla JS',
   'A calm, multi-tenant outreach pipeline. Draft in your voice, send only what you approve.',
   'Postgres + RLS / Vanilla JS / Supabase',
   'Outreach breaks down when you lose the thread, not when you run out of people.',
   'Most people run outreach out of a spreadsheet and a dozen browser tabs, and the tracking, not the typing, is what quietly eats the day. Invitovate is the fix I built for myself and turned into a product: one pipeline where your own AI finds the right people and drafts each message in your voice, you approve every send, and the tool remembers everything and tells you which approach is landing. A real multi-tenant SaaS on Postgres, live at invitovate.com.',
   'Solo build, end to end: product design, marketing site, multi-tenant backend, the console, and a background runner.',
   'A Postgres-backed SaaS with per-user row-level security, an event-sourced status pipeline, and an eval gate on every drafted message.',
   'A live product that turns scattered outreach into one calm, trackable pipeline.',
   array['Multi-Tenant SaaS','Postgres + RLS','Event-Sourced Pipeline','Vanilla JS'],
   array['Supabase/Postgres','Row-Level Security','Vanilla JavaScript'],
   'deployed',
   'LIVE PRODUCT',
   10,
   true,
   'https://invitovate.com',
   true,
   true,
   'site'),

  ('MSN-02',
   'Overheard',
   'BigQuery / Vertex AI (Gemini)',
   'Finds and ranks the customer questions brands ignore on their own social posts. 17 brands, live.',
   'BigQuery / Vertex AI (Gemini) / Apify / Python',
   'Customers ask brands questions in public. Most never get an answer.',
   'Every day customers ask questions under a brand''s own YouTube videos and Instagram posts, and brands miss a huge share of them. Social teams know it hurts but cannot put a number on it. Overheard measures it: it collects the public conversation on a set of competing brands'' own posts, uses Gemini to tell a real question or complaint from noise, checks whether the brand ever replied, and ranks the field by who answers and who goes silent.',
   'Solo build, end to end: pipeline, AI layer, marts, and the front-end tool.',
   'An ELT pipeline on BigQuery with a Gemini classification layer, validated against a hand-labeled set.',
   'A live index of which brands ignore their customers, and the exact comments they missed.',
   array['17 Brands','3,000+ Comments','BigQuery + Vertex AI','Gemini Classified'],
   array['BigQuery','Vertex AI / Gemini','Python'],
   'deployed',
   'LIVE TOOL',
   20,
   true,
   'https://pranavkaja.com/overheard',
   true,
   true,
   'site'),

  ('MSN-03',
   'CPK Production Planner',
   'In-Browser Tool / JS',
   'Order report in, make lists and pick sheets out, across 36 locations.',
   'Vanilla JS / In-Browser',
   'Paste the day''s order report, get every production sheet.',
   'A live tool that replaces a hand-built 39-tab spreadsheet for a commissary kitchen. Paste the daily order recap and it builds the DC and retail make lists, plus bread, prep, fruit, packout and stickers, across 36 campus locations. It runs entirely in the browser, nothing is sent anywhere.',
   'Solo build, end to end',
   'Parses the order recap and pivots it into per-station production sheets, all client-side',
   'A 39-tab manual spreadsheet replaced by an instant, in-browser planner',
   array['Live Tool','36 Locations','In-Browser','Zero Backend'],
   array['Vanilla JavaScript','Client-Side Parsing','Process Automation'],
   'deployed',
   'LIVE TOOL',
   30,
   true,
   'https://pranavkaja.com/projects/cpk-production',
   true,
   true,
   'site'),

  ('MSN-04',
   'Fraud Triage',
   'XGBoost / Gemini',
   '0.978 AUC; caught fraud the base model missed.',
   'XGBoost / Google Gemini / Python',
   'A two-stage pipeline that catches what the model misses.',
   'Built on 284,807 real card transactions. XGBoost scores every transaction at scale; a reasoning layer reviews only the high-risk flags and writes a structured, analyst-ready verdict. Weighted loss took AUC from 0.60 to 0.978, and in testing the second layer caught a fraud the model had scored a perfect 0.000000.',
   'Solo build, end to end',
   'Weighted-loss XGBoost plus a triage layer with strict JSON output',
   'Industry-grade AUC with a reasoning trail analysts can audit',
   array['0.978 AUC','84% Recall','84% Precision','284K Records','~2s Latency'],
   array['XGBoost','Google Gemini','Python'],
   'deployed',
   null,
   40,
   true,
   'https://github.com/PranavKaja/fraud-triage',
   false,
   true,
   'github'),

  ('MSN-05',
   'Corporate Analytics',
   'Power BI / SQL',
   '30% faster executive reviews via custom dashboards.',
   'Power BI / DAX / SQL',
   '30% faster executive reviews via custom dashboards.',
   'Executive Power BI dashboards built on live B2B data streams for TapInnovations, replacing a legacy spreadsheet workflow. Custom DAX measures gave leadership direct visibility into cross-functional throughput, and weekly performance reviews accelerated by 30%.',
   'Analyst + stakeholder liaison',
   'Custom DAX measures on live B2B data streams',
   'Weekly executive reviews 30% faster, spreadsheets retired',
   array['30% Faster Reviews','Live B2B Streams','Custom DAX','Exec-Ready'],
   array['Power BI','DAX','SQL'],
   'deployed',
   null,
   50,
   true,
   null,
   false,
   true,
   'github'),

  ('MSN-06',
   'Hospital Readmission',
   'Python / Gradient Boosting',
   '90% recall on readmissions via threshold tuning.',
   'Python / Scikit-learn / Gradient Boosting',
   '90% recall on readmissions through threshold tuning.',
   'Readmission risk on 25,000 anonymized encounters, a Python rebuild of a tool-based analysis. Logistic Regression, Random Forest, and Gradient Boosting were compared; the champion (Gradient Boosting, ROC-AUC 0.66) was threshold-tuned to catch 90% of readmissions, the costly case to miss. Prior inpatient visits, medication count, and lab procedures were the dominant drivers.',
   'Solo analysis',
   'Three-model comparison with a recall-tuned decision threshold',
   '90% of readmissions caught (ROC-AUC 0.66) before discharge',
   array['25K Records','90% Recall','ROC-AUC 0.66','Threshold Tuned'],
   array['Python','Scikit-learn','Gradient Boosting'],
   'deployed',
   null,
   60,
   true,
   'https://github.com/PranavKaja/hospital-readmission',
   false,
   true,
   'github'),

  ('MSN-07',
   'Auto Insurance Churn',
   'Gradient Boosting / SMOTE',
   'ROC-AUC 0.70 on 92,849 policyholders.',
   'Scikit-learn / Gradient Boosting / SMOTE',
   'Churn modeling on 92,849 policyholders.',
   'Five classifiers on 92,849 policyholder records with severe class imbalance (11.5% churn). A SMOTE pipeline plus a data-leakage fix (dropping a column only set after churn) put Gradient Boosting on top at ROC-AUC 0.70, threshold-tuned for recall, replacing an earlier run that had crowned a near-random model.',
   'Solo build',
   'Five-model comparison on a SMOTE pipeline, champion chosen by ROC-AUC',
   'Gradient Boosting champion at ROC-AUC 0.70, tuned for recall',
   array['92.8K Records','ROC-AUC 0.70','SMOTE Pipeline','GB Champion'],
   array['Scikit-learn','Gradient Boosting','SMOTE'],
   'deployed',
   null,
   70,
   true,
   'https://github.com/PranavKaja/insurance-churn',
   false,
   true,
   'github'),

  ('MSN-08',
   'Supply Chain Opt.',
   'HBP Simulation / Python',
   '34% cumulative margin across 4-year horizon.',
   'HBP Simulation / Inventory Strategy',
   '34% cumulative margin across a 4-year horizon.',
   'Managed a simulated global supply chain through four years of high demand volatility. A hybrid sourcing strategy with statistical inventory buffering held a 98% service level with zero stockouts while maximizing gross margin.',
   'Strategy lead',
   'Hybrid sourcing with statistical inventory buffering',
   '34% margin at a 98% service level, zero stockouts',
   array['34% Margin','98% Service Level','Zero Stockouts','Hybrid Sourcing'],
   array['HBP Simulation','Inventory Strategy'],
   'deployed',
   null,
   80,
   true,
   null,
   false,
   true,
   'github'),

  ('MSN-09',
   'Bullwhip Mitigation',
   'HBP Simulation / Sourcing',
   '54% gross margin under demand volatility.',
   'HBP Simulation / Sourcing Strategy',
   '54% gross margin under demand volatility.',
   'A four-year product lifecycle and supplier risk simulation. Engineered a hybrid sourcing strategy balancing low-cost overseas suppliers against high-flexibility nearshore ones, managing product design upgrades and volatile demand to close at a 54% cumulative gross margin.',
   'Strategy lead',
   'Hybrid sourcing balanced across offshore and nearshore suppliers',
   '54% cumulative gross margin under the bullwhip effect',
   array['54% Gross Margin','Hybrid Sourcing','4-Year Horizon','Supplier Risk'],
   array['HBP Simulation','Sourcing Strategy'],
   'deployed',
   null,
   90,
   true,
   null,
   false,
   true,
   'github'),

  ('MSN-10',
   'Prime Air Drone Logistics',
   'Geospatial / Network Design',
   '3-hub network covering 7.9% of Massachusetts.',
   'Geospatial Analysis / Folium / Python',
   'A hub-and-spoke drone network covering 7.9% of Massachusetts.',
   'Last-mile feasibility study for suburban drone delivery in Massachusetts. A multi-criteria scoring model (demand, tech/income readiness, operational feasibility) ranks candidate cities and sites three hubs (Cambridge, Worcester, Springfield), one per region, within the MK30''s 7.5-mile radius; a reproducible coverage model projects ~1,900 packages/day across 550,000 residents, rendered as an interactive map.',
   'Network designer',
   'Multi-criteria scoring (demand, readiness, feasibility) with a reproducible coverage model',
   'Three-hub model reaching ~550K residents (7.9% of MA), with an interactive map',
   array['3 Hubs','7.5-mi Radius','~1,900 Pkgs/Day','Interactive Map'],
   array['Geospatial Analysis','Folium','Python'],
   'deployed',
   null,
   100,
   true,
   'https://github.com/PranavKaja/prime-air-coverage',
   false,
   true,
   'github'),

  ('MSN-11',
   'Strategy Summit',
   'CAPSIM Simulation / Strategy',
   '483% stock recovery; top-3 of 8 teams.',
   'CAPSIM Simulation / Pricing / Capacity',
   '483% stock recovery, top-3 of 8 teams.',
   'Ran a simulated sensor manufacturer across R&D, marketing, production, and finance for five simulated years. Calibrated pricing tiers and capacity against rate-sensitive demand, recovering the share price from $1.40 to $8.17 and finishing top-3 in cumulative profit. Recognized for an alternating high-tech product strategy.',
   'Team decision lead',
   'Pricing and capacity calibration across 5 simulated years',
   'Share price from $1.40 to $8.17, top-3 cumulative profit',
   array['483% Recovery','$1.40 to $8.17','Top-3 of 8','5 Sim Years'],
   array['CAPSIM Simulation','Pricing','Capacity'],
   'archived',
   null,
   110,
   true,
   'https://www.isenberg.umass.edu/news/2026-strategy-summit',
   false,
   true,
   'site'),

  ('MSN-12',
   'Heart Disease Prediction',
   'Python / Scikit-learn',
   '~82% accuracy; best of 5 models; live Flask app.',
   'Python / Scikit-learn / Flask',
   '~82% accuracy, deployed as a Flask app.',
   'End-to-end capstone comparing five classifiers on the 13-feature clinical heart dataset. Random Forest was the strongest at ~82% accuracy; a top-3 majority-vote ensemble landed just behind, served through a Flask web app that scores risk from a 13-field form.',
   'Capstone lead',
   'Five-model comparison on a 13-feature clinical set, served via Flask',
   '~82% Random Forest accuracy, best of five models, in a live app',
   array['~82% Accuracy','5 Models Compared','13 Features','Flask App'],
   array['Python','Scikit-learn','Flask'],
   'archived',
   null,
   120,
   true,
   'https://github.com/PranavKaja/heart-disease',
   false,
   true,
   'github')
on conflict (code) do update set
  title = excluded.title, tech = excluded.tech, summary = excluded.summary,
  stack = excluded.stack, hook = excluded.hook, brief = excluded.brief,
  role = excluded.role, method = excluded.method, outcome = excluded.outcome,
  chips = excluded.chips, skills = excluded.skills, status = excluded.status,
  status_label = excluded.status_label, sort_order = excluded.sort_order,
  published = excluded.published, github_url = excluded.github_url,
  show_status = excluded.show_status, show_github = excluded.show_github,
  link_type = excluded.link_type;
