/* ============================================================================
   data.js  —  All portfolio content, compiled into one global object.
   Inlined (not fetched) so the site runs from file:// with no server.
   Source of record: 02-Website/portfolio/data/*.json + index.html copy.
   ========================================================================== */

window.PRANAV = {
  identity: {
    name: "Pranav Kaja",
    title: "Data & Analytics Engineer",
    tagline: "Translating complex data into clear action since 2020.",
    location: "Boston, MA",
    email: "balajipranavreddyk@gmail.com",
    linkedin: "https://linkedin.com/in/pranavkaja",
    github: "https://github.com/PranavKaja",
    portfolio: "https://pranavkaja.vercel.app",
    resume: "assets/Resume_Base.pdf",
  },

  about: {
    vitals: [
      ["Designation", "Data & Analytics Engineer"],
      ["Education", "MS Business Analytics · GPA 4.00"],
      ["Origin", "BTech, Computer Science"],
      ["Base", "Boston, MA"],
      ["Status", "Open to Full-Time Roles"],
    ],
    story:
      "I started in computer science and moved into business analytics, and finished my MS at UMass Amherst to bridge writing code and driving strategy. I care less about the model that looks perfect on a slide, and more about the one that survives contact with real data.",
    approach:
      "Pragmatism over perfection, but pragmatism doesn't mean cutting corners. A model that ships and gets monitored beats a perfect one stuck in a notebook. I build for the whole lifecycle and leave an audit trail the next person can actually read.",
  },

  experience: [
    {
      dates: "SEP 2024 - MAY 2026",
      org: "UMass Amherst Dining",
      role: "Student Supervisor",
      points: [
        "Automated a 37-location ETL pipeline, cutting manual reporting from 2 hrs/day to 12 min/day.",
        "Led a team of student employees and implemented data-driven inventory forecasting.",
      ],
    },
    {
      dates: "MAY 2022 - JUL 2022",
      org: "Acmegrade",
      role: "Data Science Intern",
      points: [
        "Built a Random Forest churn predictor on 100K records.",
        "Improved model accuracy 15% over baseline.",
      ],
    },
  ],

  // Projects: ordered for display. Full data carried from projects.json.
  projects: [
    {
      code: "MSN-01", title: "Fraud Triage", stack: "XGBoost / Google Gemini / Python",
      status: "in_progress",
      hook: "A two-stage pipeline that catches what the model misses.",
      brief: "Built on 284,807 real card transactions. XGBoost scores every transaction at scale; a reasoning layer reviews only the high-risk flags and writes a structured, analyst-ready verdict. Weighted loss took AUC from 0.60 to 0.978, and in testing the second layer caught a fraud the model had scored a perfect 0.000000.",
      role: "Solo build, end to end",
      method: "Weighted-loss XGBoost plus a triage layer with strict JSON output",
      outcome: "Industry-grade AUC with a reasoning trail analysts can audit",
      chips: ["0.978 AUC", "84% Recall", "84% Precision", "284K Records", "~2s Latency"],
      skills: ["XGBoost", "Google Gemini", "Python"],
      github: "https://github.com/PranavKaja/fraud-triage",
    },
    {
      code: "MSN-02", title: "Corporate Analytics", stack: "Power BI / DAX / SQL",
      status: "deployed",
      hook: "30% faster executive reviews via custom dashboards.",
      brief: "Executive Power BI dashboards built on live B2B data streams for TapInnovations, replacing a legacy spreadsheet workflow. Custom DAX measures gave leadership direct visibility into cross-functional throughput, and weekly performance reviews accelerated by 30%.",
      role: "Analyst + stakeholder liaison",
      method: "Custom DAX measures on live B2B data streams",
      outcome: "Weekly executive reviews 30% faster, spreadsheets retired",
      chips: ["30% Faster Reviews", "Live B2B Streams", "Custom DAX", "Exec-Ready"],
      skills: ["Power BI", "DAX", "SQL"],
      github: null,
    },
    {
      code: "MSN-03", title: "Heart Disease Predictors", stack: "Python / Scikit-learn / Flask",
      status: "archived",
      hook: "~82% accuracy, deployed as a Flask app.",
      brief: "End-to-end capstone comparing five classifiers on the 13-feature clinical heart dataset. Random Forest was the strongest at ~82% accuracy; a top-3 majority-vote ensemble landed just behind, served through a Flask web app that scores risk from a 13-field form.",
      role: "Capstone lead",
      method: "Five-model comparison with a top-3 majority-vote ensemble, served via Flask",
      outcome: "~82% Random Forest accuracy; ensemble just behind, in a live app",
      chips: ["~82% Accuracy", "5 Models", "Top-3 Ensemble", "Flask App"],
      skills: ["Python", "Scikit-learn", "Flask"],
      github: "https://github.com/PranavKaja/heart-disease",
    },
    {
      code: "MSN-04", title: "Hospital Readmission", stack: "Python / Scikit-learn / Gradient Boosting",
      status: "deployed",
      hook: "90% recall on readmissions through threshold tuning.",
      brief: "Readmission risk on 25,000 anonymized encounters, a Python rebuild of a tool-based analysis. Logistic Regression, Random Forest, and Gradient Boosting were compared; the champion (Gradient Boosting, ROC-AUC 0.66) was threshold-tuned to catch 90% of readmissions, the costly case to miss. Prior inpatient visits, medication count, and lab procedures were the dominant drivers.",
      role: "Solo analysis",
      method: "Three-model comparison with a recall-tuned decision threshold",
      outcome: "90% of readmissions caught (ROC-AUC 0.66) before discharge",
      chips: ["25K Records", "90% Recall", "ROC-AUC 0.66", "Threshold Tuned"],
      skills: ["Python", "Scikit-learn", "Gradient Boosting"],
      github: "https://github.com/PranavKaja/hospital-readmission",
    },
    {
      code: "MSN-05", title: "Auto Insurance Churn", stack: "Scikit-learn / Gradient Boosting / SMOTE",
      status: "deployed",
      hook: "Churn modeling on 92,849 policyholders.",
      brief: "Five classifiers on 92,849 policyholder records with severe class imbalance (11.5% churn). A SMOTE pipeline plus a data-leakage fix (dropping a column only set after churn) put Gradient Boosting on top at ROC-AUC 0.70, threshold-tuned for recall, replacing an earlier run that had crowned a near-random model.",
      role: "Solo build",
      method: "Five-model comparison on a SMOTE pipeline, champion chosen by ROC-AUC",
      outcome: "Gradient Boosting champion at ROC-AUC 0.70, tuned for recall",
      chips: ["92.8K Records", "ROC-AUC 0.70", "SMOTE Pipeline", "GB Champion"],
      skills: ["Scikit-learn", "Gradient Boosting", "SMOTE"],
      github: "https://github.com/PranavKaja/insurance-churn",
    },
    {
      code: "MSN-06", title: "Supply Chain Optimization", stack: "HBP Simulation / Inventory Strategy",
      status: "deployed",
      hook: "34% cumulative margin across a 4-year horizon.",
      brief: "Managed a simulated global supply chain through four years of high demand volatility. A hybrid sourcing strategy with statistical inventory buffering held a 98% service level with zero stockouts while maximizing gross margin.",
      role: "Strategy lead",
      method: "Hybrid sourcing with statistical inventory buffering",
      outcome: "34% margin at a 98% service level, zero stockouts",
      chips: ["34% Margin", "98% Service Level", "Zero Stockouts", "Hybrid Sourcing"],
      skills: ["HBP Simulation", "Inventory Strategy"],
      github: null,
    },
    {
      code: "MSN-07", title: "Bullwhip Mitigation", stack: "HBP Simulation / Sourcing Strategy",
      status: "deployed",
      hook: "54% gross margin under demand volatility.",
      brief: "A four-year product lifecycle and supplier risk simulation. Engineered a hybrid sourcing strategy balancing low-cost overseas suppliers against high-flexibility nearshore ones, managing product design upgrades and volatile demand to close at a 54% cumulative gross margin.",
      role: "Strategy lead",
      method: "Hybrid sourcing balanced across offshore and nearshore suppliers",
      outcome: "54% cumulative gross margin under the bullwhip effect",
      chips: ["54% Gross Margin", "Hybrid Sourcing", "4-Year Horizon", "Supplier Risk"],
      skills: ["HBP Simulation", "Sourcing Strategy"],
      github: null,
    },
    {
      code: "MSN-08", title: "Prime Air Drone Logistics", stack: "Geospatial Analysis / Folium / Python",
      status: "deployed",
      hook: "A hub-and-spoke drone network covering 7.9% of Massachusetts.",
      brief: "Last-mile feasibility study for suburban drone delivery in Massachusetts. A multi-criteria scoring model (demand, tech/income readiness, operational feasibility) ranks candidate cities and sites three hubs (Cambridge, Worcester, Springfield), one per region, within the MK30's 7.5-mile radius; a reproducible coverage model projects ~1,900 packages/day across 550,000 residents, rendered as an interactive map.",
      role: "Network designer",
      method: "Multi-criteria scoring (demand, readiness, feasibility) with a reproducible coverage model",
      outcome: "Three-hub model reaching ~550K residents (7.9% of MA), with an interactive map",
      chips: ["3 Hubs", "7.5-mi Radius", "~1,900 Pkgs/Day", "Interactive Map"],
      skills: ["Geospatial Analysis", "Folium", "Python"],
      github: "https://github.com/PranavKaja/prime-air-coverage",
    },
    {
      code: "MSN-09", title: "Strategy Summit", stack: "CAPSIM Simulation / Pricing / Capacity",
      status: "archived",
      hook: "483% stock recovery, top-3 of 8 teams.",
      brief: "Ran a simulated sensor manufacturer across R&D, marketing, production, and finance for five simulated years. Calibrated pricing tiers and capacity against rate-sensitive demand, recovering the share price from $1.40 to $8.17 and finishing top-3 in cumulative profit. Recognized for an alternating high-tech product strategy.",
      role: "Team decision lead",
      method: "Pricing and capacity calibration across 5 simulated years",
      outcome: "Share price from $1.40 to $8.17, top-3 cumulative profit",
      chips: ["483% Recovery", "$1.40 to $8.17", "Top-3 of 8", "5 Sim Years"],
      skills: ["CAPSIM Simulation", "Pricing", "Capacity"],
      github: "https://www.isenberg.umass.edu/news/2026-strategy-summit",
    },
    {
      code: "MSN-10", title: "CPK Production Planner", stack: "Vanilla JS / In-Browser",
      status: "deployed",
      hook: "Paste the day's order report, get every production sheet.",
      brief: "A live tool that replaces a hand-built 39-tab spreadsheet for a commissary kitchen. Paste the daily order recap and it builds the DC and retail make lists, plus bread, prep, fruit, packout and stickers, across 36 campus locations. It runs entirely in the browser, nothing is sent anywhere.",
      role: "Solo build, end to end",
      method: "Parses the order recap and pivots it into per-station production sheets, all client-side",
      outcome: "A 39-tab manual spreadsheet replaced by an instant, in-browser planner",
      chips: ["Live Tool", "36 Locations", "In-Browser", "Zero Backend"],
      skills: ["JavaScript"],
      github: "https://pranavkaja.vercel.app/projects/cpk-production",
    },
  ],

  skills: [
    { category: "Data Engineering", items: ["SQL", "ETL/ELT", "Python", "Spark & Hadoop", "Data Warehousing"] },
    { category: "Analytics & BI", items: ["Power BI", "Tableau", "Power Query", "KPI Design", "Financial Modeling"] },
    { category: "Machine Learning", items: ["XGBoost", "Random Forest", "Logistic Regression", "SHAP", "SMOTE"] },
    { category: "Programming", items: ["Python", "SQL", "R", "VBA", "REST APIs", "LLM Integration"] },
    { category: "Strategy & Ops", items: ["Demand Forecasting", "Supply Chain Optimization", "Capacity Planning"] },
  ],

  certifications: [
    { name: "Data Analysis with Python", issuer: "IBM", progress: 100 },
    { name: "Intro to Big Data with Spark & Hadoop", issuer: "IBM", progress: 100 },
    { name: "Supervised Learning with scikit-learn", issuer: "DataCamp", progress: 100 },
    { name: "Ensemble Methods in Python", issuer: "DataCamp", progress: 100 },
    { name: "Introduction to Power BI", issuer: "DataCamp", progress: 100 },
    { name: "Working with Hugging Face", issuer: "DataCamp", progress: 100 },
    { name: "Database Management Essentials", issuer: "UC Colorado", progress: 100 },
    { name: "Intro to Regression with statsmodels", issuer: "DataCamp", progress: 65 },
    { name: "Web Scraping in Python", issuer: "DataCamp", progress: 30 },
    { name: "Intro to APIs in Python", issuer: "DataCamp", progress: 85 },
  ],

  interests: [
    { name: "Automotive", img: "assets/images/car.jpg", desc: "I like vehicles of all kinds and how design, aerodynamics, and mechanics come together to move them." },
    { name: "Cooking", img: "assets/images/cooking.jpg", desc: "I cook to learn where a dish comes from. The cuisines, the flavors, and the science behind them." },
    { name: "Adventure", img: "assets/images/adventure.jpg", desc: "New trails, harder routes, places I haven't been. Half the fun is the trip, half is the problem-solving." },
    { name: "Photography", img: "assets/images/photography.jpg", desc: "Light and framing do most of the work. I shoot architecture, nature, and moments that don't wait around." },
    { name: "Gaming", img: "assets/images/gaming.jpg", desc: "For me, gaming is big open worlds, tight gunplay, and the kind of lobbies that keep you saying one more." },
    { name: "Music", img: "assets/images/music.jpg", desc: "I listen for how a track is built. Rhythm, texture, melody, and the way sound sets a mood." },
    { name: "Technology", img: "assets/images/technology.jpg", desc: "I enjoy following new tech and digging into how it actually works under the hood." },
    { name: "Plants", img: "assets/images/plants.jpg", desc: "I keep a small indoor jungle and enjoy learning how each plant reacts to light, water, and care." },
  ],

  blog: [
    { title: "How This Site Works", url: "https://pranavkaja.vercel.app/blog/how-this-site-works" },
    { title: "Two-Stage Fraud Detection", url: "https://pranavkaja.vercel.app/blog/two-stage-fraud-detection" },
    { title: "Automating an ETL Pipeline", url: "https://pranavkaja.vercel.app/blog/automating-etl-pipeline" },
  ],
};
